version: "3"
services:
  azastha-info:
    build:
      dockerfile: Dockerfile
      context: ./info
    image: info
    container_name: infoc
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./client:/app

  azastha-newscycle:
    build:
      dockerfile: Dockerfile
      context: ./newscycle
    image: newscycle
    container_name: newscyclec
    ports:
      - "80:4000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./client:/app
